// <auto-generated />
using System;
using APIBlog.AcessoPostgre;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace APIBlog.Migrations
{
    [DbContext(typeof(APIBlogContext))]
    [Migration("20191223025410_Identity_Blog")]
    partial class Identity_Blog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("APIBlog.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Albuns");
                });

            modelBuilder.Entity("APIBlog.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int?>("PostagemId");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("APIBlog.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Conteudo");

                    b.Property<string>("Descricao");

                    b.Property<int?>("PostagemId");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("APIBlog.Models.Postagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlbumId");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("APIBlog.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChavePublica");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("APIBlog.Models.Comentario", b =>
                {
                    b.HasOne("APIBlog.Models.Postagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId");
                });

            modelBuilder.Entity("APIBlog.Models.Foto", b =>
                {
                    b.HasOne("APIBlog.Models.Postagem")
                        .WithMany("Fotos")
                        .HasForeignKey("PostagemId");
                });

            modelBuilder.Entity("APIBlog.Models.Postagem", b =>
                {
                    b.HasOne("APIBlog.Models.Album")
                        .WithMany("Postagens")
                        .HasForeignKey("AlbumId");
                });
#pragma warning restore 612, 618
        }
    }
}
